### ISSUE TITLE
horrible experience #cancel

### ISSUE THREAD

**Issue by domjanabi** [xAmaa/nTicTacToe#2]
i was able to cope when i found out there were no tictacs
but depression really hit when i realised i won't get any toes

dev pls fix

yours truly awaiting fix,
sprit snek

**Comment by xAmaa** [comment]
Hi, thank you for your concern and for contacting me about the
tictactoe game, unfortunately, we don't integrate real-life toes in our
games. If you do wish to get your hands on some toes I recommend buying
them online
https://www.alibaba.com/product-detail/Wholesale-Plastic-feet-mannequin-cheap-foot_60473963514.html

-Ama
